### ISSUE TITLE
Style not loading on index after deployment

### ISSUE THREAD

**Issue by Nicotu** [superhawk610/gatsby-plugin-stylable#1]
I've installed the plugin and all works fine on localhost, but as soon as I deploy the site using Netlify and refresh the url no style is loaded. I've noticed that also when I navigate to another page, all the styles load fine and even work when I come back on the first page. However, as soon as I refresh the page, styles are gone again. 

Here's the  the link to the site https://miadori-staging.netlify.com

I've added you to the repo in case you want to check the code. Let me know if you could help.
Thank you

**Comment by superhawk610** [comment]
What branch are you deploying to Netlify? On `master` and `stylable`, it doesn't look like you've enabled the plugin in your `gatsby-config.js`.

```js
module.exports = {
  siteMetadata: {
    title: 'Gatsby MobX starter',
  },
  plugins: [
    'gatsby-plugin-stylable', // <-- add this
    'gatsby-plugin-typescript',
  ],
};
```

**Comment by Nicotu** [comment]
Sorry it is on develop. That is the branch that gets built on the staging url

**Comment by superhawk610** [comment]
Good news: I can reproduce the issue, and have found a resolution.

Bad news: I'm not totally sure what fixes the issue 🙃 Working on that now, I'll update as soon as I have news.

**Comment by Nicotu** [comment]
Thank you very much for your help @superhawk610 . I can confirm everything is fixed right now
